version: '2'
services:
  frr:
    image: iwaseyusuke/frr
    build:
      context: .
      args:
        user: iwaseyusuke
    environment:
      FRR_DAEMONS: zebra
    tty: true
    network_mode: "bridge"
    privileged: true
